[global]
dataFrameSerialization = "legacy"

[server]
port = 8501
headless = true
fileWatcherType = "none"
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[theme]
base = "light"
